// ============================================================
// THE EMPIRE — Game Data & Content
// ============================================================

const GAME_DATA = {

  version: "0.1.0",
  startingCash: 100,
  startingEnergy: 10,
  maxEnergy: 10,
  energyPerDay: 10,
  timeSlotsPerDay: 4,
  timeSlotNames: ["Morning", "Midday", "Afternoon", "Evening"],

  neighborhoods: [
    {
      id: "old_market",
      name: "Old Market",
      description: "Affordable, crowded, high foot traffic. Small independent businesses line narrow streets.",
      color: "#c4956a",
      baseRent: 15,
      footTraffic: 1.3,
      demandModifier: { food: 1.2, repair: 1.1, retail: 1.3, service: 1.0 },
      reputationEffect: 0.8,
      atmosphere: "Bustling and gritty",
      unlockReputation: 0
    },
    {
      id: "riverside",
      name: "Riverside",
      description: "A developing district with rising property values and changing demographics.",
      color: "#6a9cc4",
      baseRent: 30,
      footTraffic: 1.0,
      demandModifier: { food: 1.0, repair: 0.9, retail: 1.1, service: 1.2 },
      reputationEffect: 1.0,
      atmosphere: "Transitional and uncertain",
      unlockReputation: 5
    },
    {
      id: "central_square",
      name: "Central Square",
      description: "The expensive commercial center. Wealthy customers, strong competitors, prime real estate.",
      color: "#c4a86a",
      baseRent: 60,
      footTraffic: 0.9,
      demandModifier: { food: 0.9, repair: 0.7, retail: 0.8, service: 1.4 },
      reputationEffect: 1.3,
      atmosphere: "Polished and competitive",
      unlockReputation: 25
    }
  ],

  locations: [
    {
      id: "rented_room",
      name: "Your Room",
      neighborhood: "old_market",
      description: "A small rented room above a printing shop. It's humble, but it's yours.",
      icon: "🏠",
      actions: ["rest", "review_finances", "save_game"],
      alwaysAvailable: true,
      isHome: true
    },
    {
      id: "public_market",
      name: "Public Market",
      neighborhood: "old_market",
      description: "The bustling open-air market. Cheap goods, sharp vendors, endless opportunity.",
      icon: "🏪",
      actions: ["buy_goods", "sell_goods", "temp_job", "meet_character"],
      characters: ["maria_voss"],
      availableTimeSlots: [0, 1, 2]
    },
    {
      id: "corner_cafe",
      name: "Corner Café",
      neighborhood: "old_market",
      description: "A cozy café where locals gather for coffee, gossip, and deals.",
      icon: "☕",
      actions: ["meet_character", "buy_coffee", "gather_rumor"],
      characters: ["elena_kosta", "tom_brady"],
      availableTimeSlots: [0, 1, 2, 3]
    },
    {
      id: "convenience_shop",
      name: "QuickMart",
      neighborhood: "old_market",
      description: "The neighborhood convenience store. Slightly overpriced, always open.",
      icon: "🛒",
      actions: ["buy_goods", "sell_goods", "meet_character"],
      characters: ["svetlana_markov"],
      availableTimeSlots: [0, 1, 2, 3]
    },
    {
      id: "repair_workshop",
      name: "Kovač Repair",
      neighborhood: "old_market",
      description: "A cramped workshop where things get fixed — from clocks to relationships.",
      icon: "🔧",
      actions: ["temp_job", "meet_character", "hire_employee"],
      characters: ["ivan_kovac"],
      availableTimeSlots: [0, 1, 2]
    },
    {
      id: "property_office",
      name: "Harbor Properties",
      neighborhood: "riverside",
      description: "The commercial property office. Deals are struck here that reshape neighborhoods.",
      icon: "🏢",
      actions: ["buy_property", "sell_property", "meet_character", "negotiate_lease"],
      characters: ["elena_kosta"],
      availableTimeSlots: [0, 1, 2]
    },
    {
      id: "community_bank",
      name: "Community Lender",
      neighborhood: "riverside",
      description: "A local lender offering small loans with careful terms.",
      icon: "🏦",
      actions: ["request_loan", "repay_loan", "meet_character"],
      characters: ["james_chen"],
      availableTimeSlots: [0, 1, 2]
    },
    {
      id: "city_hall",
      name: "City Hall",
      neighborhood: "central_square",
      description: "Where regulations are made, permits are issued, and influence matters.",
      icon: "🏛️",
      actions: ["check_permits", "investigate_records", "meet_character"],
      characters: ["clara_dumont"],
      availableTimeSlots: [0, 1, 2]
    },
    {
      id: "local_newspaper",
      name: "The Riverside Record",
      neighborhood: "riverside",
      description: "The local newspaper. Stories start here — and sometimes end here too.",
      icon: "📰",
      actions: ["investigate", "place_ad", "meet_character"],
      characters: ["nora_petrov"],
      availableTimeSlots: [0, 1, 2, 3]
    },
    {
      id: "riverside_warehouse",
      name: "Riverside Warehouse",
      neighborhood: "riverside",
      description: "A large warehouse near the water. Currently the center of local controversy.",
      icon: "🏭",
      actions: ["investigate", "meet_character", "temp_job"],
      characters: ["dimitri_sokol", "dimitri_sokol_jr"],
      availableTimeSlots: [0, 1, 2, 3]
    },
    {
      id: "public_park",
      name: "Millbrook Park",
      neighborhood: "riverside",
      description: "A green space between neighborhoods. People relax here. People talk here.",
      icon: "🌳",
      actions: ["rest", "meet_character", "gather_rumor"],
      characters: ["karim_osman"],
      availableTimeSlots: [0, 1, 2, 3]
    },
    {
      id: "locked_tower",
      name: "Harbor Tower",
      neighborhood: "central_square",
      description: "A locked high-rise. Rumors say something important waits inside.",
      icon: "🔒",
      actions: [],
      availableTimeSlots: [],
      locked: true,
      unlockCondition: "mystery_resolved"
    }
  ],

  businesses: [
    {
      id: "market_stall",
      name: "Street Market Stall",
      category: "retail",
      description: "A simple stall in the public market. Low cost, low risk, low ceiling.",
      icon: "🏪",
      startupCost: 40,
      dailyRent: 5,
      supplyCostPerDay: 10,
      baseCustomerTraffic: 8,
      conversionRate: 0.65,
      averageSaleValue: 4,
      baseQuality: 0.6,
      capacity: 20,
      employeeSlots: 1,
      neighborhoodFit: { old_market: 1.2, riverside: 0.9, central_square: 0.5 },
      baseReputation: 2,
      upgradeLevels: 3,
      upgradeCosts: [30, 60, 120],
      upgradeBenefits: [
        { quality: 0.1, capacity: 5, description: "Better display shelf" },
        { quality: 0.15, capacity: 8, description: "Expanded product range" },
        { quality: 0.2, capacity: 12, description: "Premium goods section" }
      ],
      riskFactors: ["weather_sensitive", "theft_risk"],
      estimatedDailyProfit: "€3–8",
      requirements: { reputation: 0 }
    },
    {
      id: "coffee_cart",
      name: "Coffee Cart",
      category: "food",
      description: "A mobile coffee cart. Fast service, loyal morning customers.",
      icon: "☕",
      startupCost: 55,
      dailyRent: 3,
      supplyCostPerDay: 8,
      baseCustomerTraffic: 12,
      conversionRate: 0.7,
      averageSaleValue: 3,
      baseQuality: 0.65,
      capacity: 30,
      employeeSlots: 1,
      neighborhoodFit: { old_market: 1.1, riverside: 1.2, central_square: 0.8 },
      baseReputation: 3,
      upgradeLevels: 3,
      upgradeCosts: [25, 55, 100],
      upgradeBenefits: [
        { quality: 0.1, capacity: 8, description: "Premium bean supplier" },
        { quality: 0.15, capacity: 10, description: "Pastry partnership" },
        { quality: 0.2, capacity: 15, description: "Second cart permit" }
      ],
      riskFactors: ["seasonal_demand"],
      estimatedDailyProfit: "€4–10",
      requirements: { reputation: 2 }
    },
    {
      id: "small_cafe",
      name: "Small Café",
      category: "food",
      description: "A sit-down café with character. More customers, more complexity.",
      icon: "🧁",
      startupCost: 120,
      dailyRent: 18,
      supplyCostPerDay: 20,
      baseCustomerTraffic: 18,
      conversionRate: 0.55,
      averageSaleValue: 7,
      baseQuality: 0.7,
      capacity: 25,
      employeeSlots: 2,
      neighborhoodFit: { old_market: 1.0, riverside: 1.3, central_square: 1.1 },
      baseReputation: 8,
      upgradeLevels: 3,
      upgradeCosts: [50, 110, 200],
      upgradeBenefits: [
        { quality: 0.1, capacity: 8, description: "Expanded seating" },
        { quality: 0.15, capacity: 10, description: "Kitchen upgrade" },
        { quality: 0.2, capacity: 15, description: "Rooftop terrace" }
      ],
      riskFactors: ["staff_dependent", "inspection_risk"],
      estimatedDailyProfit: "€8–22",
      requirements: { reputation: 8 }
    },
    {
      id: "repair_service",
      name: "Repair Service",
      category: "repair",
      description: "A repair workshop. Steady demand, skilled work, loyal customers.",
      icon: "🔧",
      startupCost: 80,
      dailyRent: 12,
      supplyCostPerDay: 6,
      baseCustomerTraffic: 6,
      conversionRate: 0.8,
      averageSaleValue: 10,
      baseQuality: 0.75,
      capacity: 10,
      employeeSlots: 2,
      neighborhoodFit: { old_market: 1.3, riverside: 1.0, central_square: 0.6 },
      baseReputation: 5,
      upgradeLevels: 3,
      upgradeCosts: [40, 90, 170],
      upgradeBenefits: [
        { quality: 0.1, capacity: 4, description: "Better tools" },
        { quality: 0.15, capacity: 6, description: "Electronics repair" },
        { quality: 0.2, capacity: 8, description: "Appraisal service" }
      ],
      riskFactors: ["skill_dependent", "seasonal_lull"],
      estimatedDailyProfit: "€6–16",
      requirements: { reputation: 3 }
    },
    {
      id: "convenience_store",
      name: "Convenience Shop",
      category: "retail",
      description: "A neighborhood convenience store. Reliable income, thin margins, long hours.",
      icon: "🛒",
      startupCost: 150,
      dailyRent: 22,
      supplyCostPerDay: 25,
      baseCustomerTraffic: 22,
      conversionRate: 0.6,
      averageSaleValue: 5,
      baseQuality: 0.6,
      capacity: 35,
      employeeSlots: 2,
      neighborhoodFit: { old_market: 1.1, riverside: 1.2, central_square: 0.9 },
      baseReputation: 10,
      upgradeLevels: 3,
      upgradeCosts: [60, 130, 250],
      upgradeBenefits: [
        { quality: 0.1, capacity: 10, description: "Extended hours" },
        { quality: 0.15, capacity: 12, description: "Fresh food section" },
        { quality: 0.2, capacity: 15, description: "ATM partnership" }
      ],
      riskFactors: ["competition_sensitive", "theft_risk"],
      estimatedDailyProfit: "€5–18",
      requirements: { reputation: 10 }
    }
  ],

  characters: [
    {
      id: "maria_voss",
      name: "Maria Voss",
      role: "Experienced Shopkeeper",
      personality: "Pragmatic, warm, shrewd",
      occupation: "Owns a stall in the public market for 20 years",
      personalGoal: "Protect independent businesses from corporate takeover",
      publicInfo: "Respected elder of the Old Market community",
      hiddenInfo: "Has secretly been paying extra rent to prevent a corporate buyout",
      portrait: "👩‍🦳",
      influence: 6,
      preferredLocations: ["public_market", "convenience_shop"],
      relationships: { elena_kosta: "friendly", ivan_kovac: "friendly", svetlana_markov: "suspicious", dimitri_sokol: "wary", clara_dumont: "respectful" },
      potentialBenefit: "Mentorship, market knowledge, community connections",
      potentialConflict: "Will oppose aggressive corporate expansion",
      startingRelationship: 25,
      startingTrust: 20,
      schedule: { 0: "public_market", 1: "public_market", 2: "corner_cafe", 3: "public_market" },
      dialogueStates: {
        introduction: "So you're the new face. I've seen plenty come through here with big plans. The ones who listen last the longest.",
        friendly: "Good to see you again. How's business? I heard something interesting at the market today...",
        suspicious: "I've been watching how you operate. We'll see if you're the real deal.",
        mentor_tip: "Here's something they don't teach you: in this city, the people matter more than the profit. At least if you want to last.",
        mystery_hint: "Something's not right in Riverside. Businesses closing, but the foot traffic hasn't dropped. Someone's cooking the books.",
        upset: "I thought you understood this community. Clearly, I was wrong."
      }
    },
    {
      id: "elena_kosta",
      name: "Elena Kosta",
      role: "Ambitious Property Agent",
      personality: "Charming, driven, calculating",
      occupation: "Junior agent at Harbor Properties",
      personalGoal: "Become the most powerful property dealer in the city",
      publicInfo: "Young, successful, always closing deals",
      hiddenInfo: "Under pressure from Dimitri to steer property sales toward his network",
      portrait: "👩‍💼",
      influence: 5,
      preferredLocations: ["corner_cafe", "property_office"],
      relationships: { maria_voss: "friendly", svetlana_markov: "competitive", dimitri_sokol: "indebted", clara_dumont: "professional", james_chen: "friendly" },
      potentialBenefit: "Property opportunities, insider pricing, market predictions",
      potentialConflict: "May push deals that benefit her network over the player",
      startingRelationship: 10,
      startingTrust: 5,
      schedule: { 0: "property_office", 1: "corner_cafe", 2: "property_office", 3: "corner_cafe" },
      dialogueStates: {
        introduction: "Welcome to the city! I'm Elena. If you ever want to stop renting and start owning, you come to me.",
        friendly: "I've got something interesting on my desk. Might be perfect for someone with your ambition.",
        suspicious: "I've heard things about your business practices. Let's hope they're not true.",
        deal_offer: "There's a property in Riverside that's... undervalued. I can get you first look. But I'd need a favor in return.",
        mystery_hint: "Dimitri's been asking me to push certain properties. Properties that don't make sense on paper. But the commissions are good...",
        upset: "I put my reputation on the line for you. Don't make me regret it."
      }
    },
    {
      id: "ivan_kovac",
      name: "Ivan Kovač",
      role: "Skilled Repair Worker",
      personality: "Quiet, proud, haunted",
      occupation: "Master repair technician, currently between jobs",
      personalGoal: "Earn enough to bring his daughter from abroad",
      publicInfo: "The best repairman in Old Market. Recently left his old employer.",
      hiddenInfo: "His previous employer was forced out by Apex Retail — he suspects foul play",
      portrait: "🧔",
      influence: 2,
      preferredLocations: ["repair_workshop", "public_park"],
      relationships: { maria_voss: "respectful", karim_osman: "friendly", dimitri_sokol: "resentful", clara_dumont: "hopeful" },
      potentialBenefit: "Exceptional repair skills, loyal if treated well",
      potentialConflict: "Personal problems may affect reliability; carries grudges",
      startingRelationship: 15,
      startingTrust: 10,
      schedule: { 0: "repair_workshop", 1: "repair_workshop", 2: "public_park", 3: "corner_cafe" },
      dialogueStates: {
        introduction: "You need something fixed? I can fix almost anything. Except this city, maybe.",
        friendly: "You know, working for you... it feels different. Like I matter.",
        suspicious: "You're starting to remind me of my old boss. And that's not a compliment.",
        personal: "My daughter... she's still across the border. Every day I work is one day closer to her.",
        mystery_hint: "My old shop? Forced to sell. Apex came in, undercut everything. But the paperwork didn't add up. Someone made that sale happen.",
        upset: "I expected better from you. Clearly, money matters more than people."
      },
      isHireable: true,
      hireData: { wage: 18, skill: 9, reliability: 7, morale: 5, energy: 8, loyalty: 4, trait: "Perfectionist", growthPotential: 7, personalConcern: "Needs €200 to reunite with daughter", bestRole: "repair" }
    },
    {
      id: "nora_petrov",
      name: "Nora Petrov",
      role: "Local Journalist",
      personality: "Curious, persistent, idealistic",
      occupation: "Reporter for The Riverside Record",
      personalGoal: "Break the story that will save her newspaper",
      publicInfo: "Writes the popular 'City Pulse' column",
      hiddenInfo: "Has evidence of property fraud but needs corroboration before publishing",
      portrait: "👩‍💻",
      influence: 4,
      preferredLocations: ["local_newspaper", "public_park"],
      relationships: { clara_dumont: "suspicious", dimitri_sokol: "investigating", karim_osman: "friendly", maria_voss: "friendly" },
      potentialBenefit: "Publicity, investigation help, information network",
      potentialConflict: "May publish stories the player would prefer remained quiet",
      startingRelationship: 5,
      startingTrust: 5,
      schedule: { 0: "local_newspaper", 1: "public_park", 2: "local_newspaper", 3: "corner_cafe" },
      dialogueStates: {
        introduction: "Nora Petrov, Riverside Record. I cover the stories everyone talks about but nobody writes down.",
        friendly: "I've been following your business. Interesting moves. Want to give me a quote?",
        suspicious: "Off the record — something's happening in this city that nobody wants to talk about. Are you involved?",
        investigation: "I've been tracking property sales in Riverside. The numbers don't add up. Someone's manipulating the market.",
        mystery_hint: "I've got documents showing three properties sold well below value to the same LLC. But I can't prove who's behind it yet.",
        upset: "I trusted you with that information. And you used it for yourself. That's exactly what they do."
      }
    },
    {
      id: "karim_osman",
      name: "Karim Osman",
      role: "Community Organizer",
      personality: "Passionate, diplomatic, stubborn",
      occupation: "Runs the Riverside Community Alliance",
      personalGoal: "Keep Riverside affordable for its residents",
      publicInfo: "Champion of tenant rights and neighborhood preservation",
      hiddenInfo: "Being blackmailed into silence by someone with leverage on his immigration status",
      portrait: "👨‍🦱",
      influence: 5,
      preferredLocations: ["public_park", "city_hall"],
      relationships: { maria_voss: "allied", nora_petrov: "friendly", clara_dumont: "frustrated", dimitri_sokol: "opposed" },
      potentialBenefit: "Community support, political influence, grassroots intelligence",
      potentialConflict: "Will oppose any action that displaces residents",
      startingRelationship: 5,
      startingTrust: 10,
      schedule: { 0: "public_park", 1: "city_hall", 2: "public_park", 3: "public_park" },
      dialogueStates: {
        introduction: "Karim Osman, Riverside Community Alliance. If you're here to help, welcome. If you're here to exploit... we'll have a problem.",
        friendly: "The community's warming up to you. That's not easy to earn. Keep it up.",
        suspicious: "Riverside doesn't need another landlord who doesn't live here.",
        pressure: "They're pushing people out. Rents going up, businesses forced to close. Someone's engineering this.",
        mystery_hint: "I've received anonymous offers to 'support' our alliance. The money's good. Too good. I don't trust it.",
        upset: "You said you'd protect this neighborhood. Instead, you're part of the problem."
      }
    },
    {
      id: "james_chen",
      name: "James Chen",
      role: "Loan Officer",
      personality: "Cautious, fair, nervous",
      occupation: "Senior loan officer at the Community Lender",
      personalGoal: "Keep the bank stable while helping genuine entrepreneurs",
      publicInfo: "Known for fair terms and careful risk assessment",
      hiddenInfo: "Pressured by board members connected to the Valenti family to approve questionable loans",
      portrait: "🧑‍💼",
      influence: 4,
      preferredLocations: ["community_bank"],
      relationships: { maria_voss: "respectful", elena_kosta: "friendly", svetlana_markov: "professional", dimitri_sokol: "uncomfortable" },
      potentialBenefit: "Loan access, financial advice, credit flexibility",
      potentialConflict: "May enforce terms strictly if pressured; connected to powerful interests",
      startingRelationship: 0,
      startingTrust: 10,
      schedule: { 0: "community_bank", 1: "community_bank", 2: "community_bank", 3: "corner_cafe" },
      dialogueStates: {
        introduction: "James Chen, Community Lender. We help people who show they can manage money. Show me you can, and we'll talk.",
        friendly: "Your accounts look healthy. I might be able to offer better terms on your next loan.",
        suspicious: "Your cash flow concerns me. I'd hate to see you overextend.",
        loan_offer: "I can approve up to €200 at 8% interest. But I need to see a solid business plan.",
        mystery_hint: "Some loans I've been asked to approve... they don't make sense on paper. But the board insists. I don't like it.",
        upset: "You defaulted. That affects everyone — not just you."
      }
    },
    {
      id: "clara_dumont",
      name: "Clara Dumont",
      role: "City Official",
      personality: "Polished, pragmatic, ambitious",
      occupation: "Deputy director of the City Planning Office",
      personalGoal: "Modernize the city while advancing her political career",
      publicInfo: "Effective administrator, likely future mayoral candidate",
      hiddenInfo: "Received campaign contributions from entities linked to the Riverside scheme",
      portrait: "👩‍⚖️",
      influence: 8,
      preferredLocations: ["city_hall"],
      relationships: { nora_petrov: "uncomfortable", karim_osman: "annoyed", james_chen: "professional", dimitri_sokol: "complicated" },
      potentialBenefit: "Permits, regulatory flexibility, political cover",
      potentialConflict: "May block actions that threaten her plans or expose her connections",
      startingRelationship: -5,
      startingTrust: 0,
      schedule: { 0: "city_hall", 1: "city_hall", 2: "city_hall", 3: "corner_cafe" },
      dialogueStates: {
        introduction: "Clara Dumont, City Planning. If you want to build something in this city, you'll need to talk to me eventually.",
        friendly: "Your business contributes to our urban renewal goals. Let me know if you need any... facilitation.",
        suspicious: "I've received complaints about your operations. Nothing formal yet. Let's keep it that way.",
        political: "Modernization has costs. Some people resist change. But progress is inevitable — or so I keep telling myself.",
        mystery_hint: "I've approved developments I believed were for the public good. If someone manipulated that process... I need to know before anyone else does.",
        upset: "You've made a powerful enemy. I hope it was worth it."
      }
    },
    {
      id: "dimitri_sokol",
      name: "Dimitri Sokol",
      role: "Wealthy Investor",
      personality: "Charming, ruthless, calculating",
      occupation: "Real estate investor, silent partner in multiple ventures",
      personalGoal: "Control property in Riverside for a massive redevelopment play",
      publicInfo: "Successful businessman, major donor, respected civic figure",
      hiddenInfo: "Mastermind of the Riverside property fraud scheme",
      portrait: "🧑‍🦲",
      influence: 9,
      preferredLocations: ["riverside_warehouse", "corner_cafe"],
      relationships: { elena_kosta: "leverage", james_chen: "pressured", clara_dumont: "benefactor", karim_osman: "obstacle", nora_petrov: "threat" },
      potentialBenefit: "Capital, connections, exclusive deals — if you play his game",
      potentialConflict: "Will eventually demand loyalty; his deals always have hidden costs",
      startingRelationship: -10,
      startingTrust: -5,
      schedule: { 0: "riverside_warehouse", 1: "corner_cafe", 2: "property_office", 3: "riverside_warehouse" },
      dialogueStates: {
        introduction: "Dimitri Sokol. I hear you're making moves. I respect ambition. Let me know when you're ready for real opportunities.",
        friendly: "I could use someone like you. Smart, hungry, not yet... compromised. Let's do business.",
        suspicious: "I hear you've been asking questions. Questions can be dangerous. For everyone.",
        deal: "I'm prepared to offer you a partnership. The terms are generous. The expectations are... clear.",
        mystery_hint: "You're getting close to something. I suggest you step back. Not everyone gets a second warning.",
        upset: "You've made a serious mistake. This city has a long memory. And so do I."
      }
    },
    {
      id: "svetlana_markov",
      name: "Svetlana Markov",
      role: "Rival Business Owner",
      personality: "Sharp, competitive, vindictive",
      occupation: "Runs a chain of discount retail stores under Apex Retail",
      personalGoal: "Eliminate independent competition and dominate the retail market",
      publicInfo: "Aggressive businesswoman, expanding rapidly, known for undercutting",
      hiddenInfo: "Receives preferential supplier rates through a deal with the Valenti family",
      portrait: "👩‍🦰",
      influence: 6,
      preferredLocations: ["convenience_shop", "property_office"],
      relationships: { maria_voss: "hostile", elena_kosta: "competitive", james_chen: "friendly", dimitri_sokol: "allied" },
      potentialBenefit: "None directly — she's a rival",
      potentialConflict: "Will undercut prices, poach employees, and spread negative publicity",
      startingRelationship: -15,
      startingTrust: -10,
      schedule: { 0: "convenience_shop", 1: "property_office", 2: "convenience_shop", 3: "corner_cafe" },
      dialogueStates: {
        introduction: "Svetlana Markov, Apex Retail. I've noticed you. Small players either grow or get absorbed. Choose wisely.",
        friendly: "Perhaps we can find... common ground. After all, this city is big enough for cooperation.",
        suspicious: "Your little shop is costing me margin. I don't like that.",
        threat: "I'm opening a new location next to your best store. Let's see how your customers like our prices.",
        mystery_hint: "Dimitri promised me Riverside would be cleared for development. I invested heavily. If that falls through...",
        upset: "You've embarrassed me publicly. That's something I don't forget. Ever."
      }
    },
    {
      id: "tom_brady",
      name: "Tom Brennan",
      role: "Unreliable Information Broker",
      personality: "Friendly, slippery, cowardly",
      occupation: "Bartender and occasional informant",
      personalGoal: "Survive by staying useful to everyone",
      publicInfo: "Knows everyone, talks to everyone, trusted by no one",
      hiddenInfo: "Paid by Dimitri to report on who's asking questions about Riverside",
      portrait: "🧔‍♂️",
      influence: 2,
      preferredLocations: ["corner_cafe"],
      relationships: { dimitri_sokol: "afraid", nora_petrov: "flirty", maria_voss: "fond", karim_osman: "nervous" },
      potentialBenefit: "Rumors, gossip, early warnings about rival moves",
      potentialConflict: "Information may be inaccurate; may sell player info to rivals",
      startingRelationship: 15,
      startingTrust: -5,
      schedule: { 0: "corner_cafe", 1: "corner_cafe", 2: "corner_cafe", 3: "corner_cafe" },
      dialogueStates: {
        introduction: "Name's Brennan, but everyone calls me Tom. I know things. Useful things. Sometimes even true things.",
        friendly: "Hey, friend! Heard something at the counter you might find interesting. No charge this time.",
        suspicious: "People are asking about you. What do you want me to tell them?",
        rumor: "Word is Svetlana's planning to open right across from your place. But that's just... what I heard.",
        mystery_hint: "I probably shouldn't tell you this, but... Dimitri's been buying up Riverside properties through shell companies. Don't ask how I know.",
        upset: "You weren't supposed to say that came from me! Now I'm in trouble with some very serious people."
      }
    },
    {
      id: "lisette_valenti",
      name: "Lisette Valenti",
      role: "Family Business Leader",
      personality: "Dignified, traditional, protective",
      occupation: "Head of the Valenti family business network",
      personalGoal: "Maintain the family's influence and legacy in Old Market",
      publicInfo: "Respected community leader, oversees a network of family businesses",
      hiddenInfo: "Family is slowly losing ground and she's desperate to maintain relevance",
      portrait: "👵",
      influence: 7,
      preferredLocations: ["public_market", "corner_cafe"],
      relationships: { svetlana_markov: "business_partner", clara_dumont: "cautious", maria_voss: "complicated", james_chen: "influenced" },
      potentialBenefit: "Established network, supplier access, Old Market loyalty",
      potentialConflict: "Expects loyalty in return; family interests always come first",
      startingRelationship: -5,
      startingTrust: 0,
      schedule: { 0: "public_market", 1: "corner_cafe", 2: "public_market", 3: "corner_cafe" },
      dialogueStates: {
        introduction: "Lisette Valenti. My family has been in this market for three generations. We respect tradition. We respect loyalty.",
        friendly: "You've been good for the market. Perhaps we can formalize our... understanding.",
        suspicious: "The old ways aren't always popular. But they're reliable. Can you say the same about your methods?",
        alliance: "Join our supplier network. Better prices, reliable delivery. All I ask is... consideration.",
        mystery_hint: "Dimitri approached us about Riverside. We refused. Some deals carry a price that's too high — even for us.",
        upset: "You chose them over us. Remember that when you need friends in this city."
      }
    },
    {
      id: "dimitri_sokol_jr",
      name: "Alexei Volkov",
      role: "Mystery-Connected Character",
      personality: "Intense, intelligent, trapped",
      occupation: "Former accountant, now hiding in plain sight",
      personalGoal: "Expose the truth without getting himself killed",
      publicInfo: "Quiet man who works odd jobs around the warehouse district",
      hiddenInfo: "Former accountant for Sokol's shell companies — he has the key documents",
      portrait: "🧑",
      influence: 1,
      preferredLocations: ["riverside_warehouse", "public_park"],
      relationships: { dimitri_sokol: "terrified", nora_petrov: "wants_to_contact", karim_osman: "grateful" },
      potentialBenefit: "Critical evidence for the mystery, insider testimony",
      potentialConflict: "Fearful and unreliable under pressure; may flee if threatened",
      startingRelationship: 0,
      startingTrust: -10,
      schedule: { 0: "riverside_warehouse", 1: "public_park", 2: "riverside_warehouse", 3: "riverside_warehouse" },
      dialogueStates: {
        introduction: "...Who are you? I don't talk to people. Not anymore.",
        friendly: "You're... not like the others. Maybe I can trust you. But not here. Not now.",
        suspicious: "Did he send you? I won't go back. I won't.",
        revelation: "I have the ledgers. The real ones. They show everything — every shell company, every below-value sale, every fake expense. But if he finds out I have them...",
        mystery_hint: "The properties are being moved through three companies: Riverside Holdings, Delta Development, and Meridian Properties. All controlled by the same person. I can prove it.",
        upset: "You promised to protect me. And then you went straight to him. I can't trust anyone."
      }
    }
  ],

  employeeCandidates: [
    {
      id: "ivan_kovac",
      name: "Ivan Kovač",
      characterId: "ivan_kovac",
      portrait: "🧔",
      wage: 18, skill: 9, reliability: 7, morale: 5, energy: 8, loyalty: 4,
      trait: "Perfectionist",
      growthPotential: 7,
      personalConcern: "Needs €200 to reunite with daughter",
      bestRole: "repair",
      hireCost: 0
    },
    {
      id: "sophie_laurent",
      name: "Sophie Laurent",
      characterId: null,
      portrait: "👩",
      wage: 15, skill: 6, reliability: 8, morale: 7, energy: 9, loyalty: 6,
      trait: "Early Bird",
      growthPotential: 5,
      personalConcern: "Saving for nursing school",
      bestRole: "food",
      hireCost: 0
    },
    {
      id: "marco_rossi",
      name: "Marco Rossi",
      characterId: null,
      portrait: "👨‍🦱",
      wage: 14, skill: 5, reliability: 6, morale: 6, energy: 7, loyalty: 5,
      trait: "People Person",
      growthPotential: 6,
      personalConcern: "Supporting his mother",
      bestRole: "retail",
      hireCost: 0
    },
    {
      id: "hana_kim",
      name: "Hana Kim",
      characterId: null,
      portrait: "👩‍🔧",
      wage: 16, skill: 7, reliability: 9, morale: 8, energy: 7, loyalty: 7,
      trait: "Detail-Oriented",
      growthPotential: 8,
      personalConcern: "Wants to open her own shop someday",
      bestRole: "retail",
      hireCost: 0
    },
    {
      id: "felix_braun",
      name: "Felix Braun",
      characterId: null,
      portrait: "🧑‍🦱",
      wage: 12, skill: 4, reliability: 5, morale: 6, energy: 8, loyalty: 3,
      trait: "Opportunist",
      growthPotential: 4,
      personalConcern: "Always looking for a better deal",
      bestRole: "any",
      hireCost: 0
    },
    {
      id: "ava_thompson",
      name: "Ava Thompson",
      characterId: null,
      portrait: "👩‍🦱",
      wage: 20, skill: 8, reliability: 9, morale: 9, energy: 6, loyalty: 8,
      trait: "Loyal",
      growthPotential: 9,
      personalConcern: "Caring for sick father",
      bestRole: "food",
      hireCost: 0
    }
  ],

  rivalOrganizations: [
    {
      id: "valenti_family",
      name: "The Valenti Network",
      type: "family",
      description: "An established family-owned business network with deep roots in Old Market.",
      icon: "🤝",
      money: 5000, influence: 7,
      preferredNeighborhoods: ["old_market"],
      businessInterests: ["retail", "food"],
      attitude: "cautious",
      personality: "traditional",
      leaderId: "lisette_valenti",
      relationships: { apex_retail: "business_deal", riverside_coop: "dismissive" },
      possibleActions: [
        { action: "offer_supplier_deal", effect: "reduced_supply_cost", cost: 0, condition: "relationship > 20" },
        { action: "undercut_prices", effect: "reduced_customer_traffic", cost: 100, condition: "threatened" },
        { action: "recruit_employee", effect: "lose_employee", cost: 50, condition: "employee_low_loyalty" },
        { action: "spread_rumor", effect: "reputation_-5", cost: 30, condition: "relationship < -20" },
        { action: "offer_alliance", effect: "alliance_available", cost: 0, condition: "relationship > 40" }
      ],
      allianceCondition: "relationship >= 40 and shared_neighborhood",
      neutralityCondition: "relationship >= -10",
      hostilityCondition: "relationship < -20 or threatening_core_business"
    },
    {
      id: "apex_retail",
      name: "Apex Retail Group",
      type: "corporate",
      description: "An aggressive modern retail group expanding rapidly across all neighborhoods.",
      icon: "📊",
      money: 8000, influence: 6,
      preferredNeighborhoods: ["old_market", "riverside"],
      businessInterests: ["retail", "food"],
      attitude: "aggressive",
      personality: "expansionist",
      leaderId: "svetlana_markov",
      relationships: { valenti_family: "business_deal", riverside_coop: "hostile" },
      possibleActions: [
        { action: "open_competing_store", effect: "reduced_market_share", cost: 500, condition: "player_has_same_business_type" },
        { action: "price_war", effect: "reduced_sale_value", cost: 200, condition: "same_neighborhood" },
        { action: "poach_employee", effect: "lose_employee", cost: 100, condition: "employee_low_morale" },
        { action: "negative_publicity", effect: "reputation_-8", cost: 50, condition: "player_growing" },
        { action: "acquisition_offer", effect: "buyout_available", cost: 0, condition: "player_struggling" }
      ],
      allianceCondition: "relationship >= 50 or player_dominant",
      neutralityCondition: "relationship >= 0",
      hostilityCondition: "relationship < -10 or competing_directly"
    },
    {
      id: "riverside_coop",
      name: "Riverside Cooperative",
      type: "community",
      description: "A neighborhood cooperative fighting to keep Riverside affordable and independent.",
      icon: "🌱",
      money: 1500, influence: 5,
      preferredNeighborhoods: ["riverside"],
      businessInterests: ["food", "service"],
      attitude: "defensive",
      personality: "community_first",
      leaderId: "karim_osman",
      relationships: { valenti_family: "dismissive", apex_retail: "hostile" },
      possibleActions: [
        { action: "boycott", effect: "reduced_customer_traffic", cost: 0, condition: "player_harming_community" },
        { action: "community_event", effect: "increased_reputation", cost: 50, condition: "relationship > 10" },
        { action: "employee_strike", effect: "business_closed_day", cost: 0, condition: "employee_mistreated" },
        { action: "offer_partnership", effect: "community_deal", cost: 0, condition: "relationship > 30" },
        { action: "public_protest", effect: "reputation_-10", cost: 0, condition: "player_displacing_residents" }
      ],
      allianceCondition: "relationship >= 30 and community_friendly",
      neutralityCondition: "relationship >= 0",
      hostilityCondition: "relationship < -15 or harming_residents"
    }
  ],

  properties: [
    { id: "market_stall_space", name: "Market Stall Space", neighborhood: "old_market", type: "commercial", price: 30, rentPerDay: 5, description: "A designated stall space in the public market.", available: true },
    { id: "old_shop_front", name: "Old Shop Front", neighborhood: "old_market", type: "commercial", price: 200, rentPerDay: 0, description: "A small street-level shop with character. Own it outright.", available: true },
    { id: "riverside_storefront", name: "Riverside Storefront", neighborhood: "riverside", type: "commercial", price: 350, rentPerDay: 0, description: "A modern storefront in an up-and-coming block. Values are rising.", available: true, mysteryConnected: true },
    { id: "riverside_warehouse_lease", name: "Warehouse Lease", neighborhood: "riverside", type: "warehouse", price: 0, rentPerDay: 25, description: "A large warehouse space near the waterfront. Expensive but versatile.", available: true, mysteryConnected: true },
    { id: "central_office", name: "Central Square Office", neighborhood: "central_square", type: "office", price: 600, rentPerDay: 0, description: "A prestigious office space. The address alone opens doors.", available: false, unlockCondition: "reputation >= 25" },
    { id: "riverside_apartment", name: "Riverside Apartment", neighborhood: "riverside", type: "residential", price: 150, rentPerDay: 0, description: "A modest apartment. Better than your rented room.", available: true },
    { id: "old_market_loft", name: "Old Market Loft", neighborhood: "old_market", type: "mixed", price: 280, rentPerDay: 0, description: "A loft space above a shop. Live upstairs, work downstairs.", available: true },
    { id: "harbor_tower_unit", name: "Harbor Tower Unit", neighborhood: "central_square", type: "premium", price: 1200, rentPerDay: 0, description: "The locked building's penthouse. The mystery must be resolved first.", available: false, unlockCondition: "mystery_resolved" }
  ],

  loanOffers: [
    { id: "micro", name: "Micro Loan", amount: 100, interestRate: 0.1, termDays: 10, minReputation: 0, minRelationship: 0 },
    { id: "small", name: "Small Business Loan", amount: 250, interestRate: 0.08, termDays: 20, minReputation: 5, minRelationship: 10 },
    { id: "growth", name: "Growth Loan", amount: 500, interestRate: 0.07, termDays: 30, minReputation: 15, minRelationship: 20 },
    { id: "major", name: "Major Development Loan", amount: 1000, interestRate: 0.06, termDays: 45, minReputation: 30, minRelationship: 40 }
  ],

  tempJobs: [
    { id: "market_helper", name: "Market Helper", location: "public_market", pay: 12, energyCost: 2, timeSlots: [0, 1], description: "Help vendors set up and serve customers." },
    { id: "delivery_runner", name: "Delivery Runner", location: "public_market", pay: 10, energyCost: 2, timeSlots: [0, 1, 2], description: "Deliver packages across the neighborhood." },
    { id: "repair_assistant", name: "Repair Assistant", location: "repair_workshop", pay: 15, energyCost: 3, timeSlots: [0, 1, 2], description: "Assist with basic repairs. Harder work, better pay." },
    { id: "cafe_server", name: "Café Server", location: "corner_cafe", pay: 8, energyCost: 1, timeSlots: [1, 2], description: "Serve coffee and pastries. Easy work, modest pay." },
    { id: "warehouse_worker", name: "Warehouse Worker", location: "riverside_warehouse", pay: 18, energyCost: 3, timeSlots: [0, 1], description: "Heavy lifting at the warehouse. Good money, tough work." }
  ],

  mysteryClues: [
    { id: "clue_1", title: "Failing Businesses, Strong Traffic", type: "factual", description: "Three Riverside businesses closed this quarter despite healthy customer counts.", source: "observation", location: "riverside", reliability: 1.0, discoverable: true, discoveryMethod: "visit_riverside", connections: ["clue_2", "clue_4", "clue_7"] },
    { id: "clue_2", title: "Property Value Anomaly", type: "factual", description: "Riverside property values dropped 15% in areas near recent closures, while surrounding values rose.", source: "public_records", location: "city_hall", reliability: 1.0, discoverable: true, discoveryMethod: "investigate_records", connections: ["clue_1", "clue_3", "clue_5"] },
    { id: "clue_3", title: "Shell Company Trail", type: "factual", description: "Three companies — Riverside Holdings, Delta Development, Meridian Properties — bought closed business properties at below-market prices.", source: "alexei_volkov", location: "riverside_warehouse", reliability: 0.9, discoverable: true, discoveryMethod: "talk_to_alexei", requiredTrust: 15, connections: ["clue_2", "clue_8", "clue_11"] },
    { id: "clue_4", title: "Employee Testimony", type: "incomplete", description: "A former café owner says she was offered a buyout that seemed too good, then her rent doubled when she refused.", source: "karim_osman", location: "public_park", reliability: 0.8, discoverable: true, discoveryMethod: "talk_to_karim", requiredTrust: 10, connections: ["clue_1", "clue_5", "clue_9"] },
    { id: "clue_5", title: "Rent Spike Pattern", type: "factual", description: "Rents in Riverside increased 30% in the last six months, but only for businesses that refused buyout offers.", source: "public_records", location: "city_hall", reliability: 1.0, discoverable: true, discoveryMethod: "investigate_records", connections: ["clue_2", "clue_4", "clue_10"] },
    { id: "clue_6", title: "Competitor's Good Fortune", type: "misleading", description: "Apex Retail's expansion coincided perfectly with Riverside closures. They must be behind it!", source: "tom_brady", location: "corner_cafe", reliability: 0.4, discoverable: true, discoveryMethod: "gather_rumor", connections: ["clue_7", "clue_9"] },
    { id: "clue_7", title: "Dimitri's Public Philanthropy", type: "misleading", description: "Dimitri Sokol donated heavily to Riverside community programs. He's clearly a benefactor, not a threat.", source: "public_info", location: "public_park", reliability: 0.3, discoverable: true, discoveryMethod: "visit_riverside", connections: ["clue_1", "clue_6"] },
    { id: "clue_8", title: "The Ledgers", type: "factual", description: "Authentic accounting ledgers showing all three shell companies funnel profits to a single account controlled by D. Sokol.", source: "alexei_volkov", location: "riverside_warehouse", reliability: 1.0, discoverable: true, discoveryMethod: "earn_alexei_trust", requiredTrust: 40, timeSensitive: true, connections: ["clue_3", "clue_11", "clue_12"] },
    { id: "clue_9", title: "Elena's Pressure", type: "incomplete", description: "Elena seems stressed about certain property deals. She mentioned being 'caught between promises.'", source: "elena_kosta", location: "corner_cafe", reliability: 0.7, discoverable: true, discoveryMethod: "talk_to_elena", requiredTrust: 20, connections: ["clue_4", "clue_6", "clue_10"] },
    { id: "clue_10", title: "Permit Irregularity", type: "factual", description: "Development permits for Riverside were approved unusually fast — bypassing standard review periods.", source: "city_hall_records", location: "city_hall", reliability: 0.9, discoverable: true, discoveryMethod: "investigate_records", requiredInfluence: 10, connections: ["clue_5", "clue_9", "clue_11"] },
    { id: "clue_11", title: "Clara's Campaign Connection", type: "time_sensitive", description: "Campaign finance records show donations from Delta Development to Clara Dumont's political fund, dated just before the fast-tracked permits.", source: "investigation", location: "local_newspaper", reliability: 0.85, discoverable: true, discoveryMethod: "deep_investigation", requiredKnowledge: 5, timeSensitive: true, connections: ["clue_3", "clue_8", "clue_10"] },
    { id: "clue_12", title: "Karim's Blackmail", type: "dependent_on_trust", description: "Karim reveals he was offered money to stop organizing — and threatened with immigration status exposure if he continued.", source: "karim_osman", location: "public_park", reliability: 0.95, discoverable: true, discoveryMethod: "earn_karim_trust", requiredTrust: 50, connections: ["clue_4", "clue_11"] }
  ],

  mysteryResolutions: [
    {
      id: "public_expose",
      name: "Public Exposure",
      description: "Publish all evidence through The Riverside Record. The scheme becomes public knowledge.",
      requiredClues: ["clue_3", "clue_8", "clue_10"],
      consequences: {
        reputation: 15, influence: 10,
        dimitri_sokol_relationship: -50, clara_dumont_relationship: -30,
        nora_petrov_relationship: 30, karim_osman_relationship: 20,
        svetlana_markov_relationship: -10,
        propertyEffect: "riverside_values_stabilize",
        rivalEffect: "apex_weakened",
        narrativeSummary: "The truth is out. Dimitri's empire crumbles as investigations begin. Clara's political career is damaged. The community feels vindicated, but powerful enemies now know your name."
      }
    },
    {
      id: "private_negotiate",
      name: "Private Negotiation",
      description: "Use the evidence as leverage to negotiate Dimitri's exit from Riverside and property restitution.",
      requiredClues: ["clue_3", "clue_5", "clue_8"],
      consequences: {
        reputation: 5, influence: 20,
        dimitri_sokol_relationship: -20, clara_dumont_relationship: 0,
        nora_petrov_relationship: -15, karim_osman_relationship: 5,
        cash: 500,
        propertyEffect: "riverside_properties_returned",
        rivalEffect: "dimitri_withdraws",
        narrativeSummary: "Dimitri retreats from Riverside, returning properties to their original owners. You gain significant influence and a cash settlement. But Nora is furious — the public never learns the truth, and Dimitri walks away wealthy."
      }
    },
    {
      id: "protect_informant",
      name: "Protect and Resolve",
      description: "Protect Alexei and Karim while dismantling the scheme through legal channels, shielding the vulnerable.",
      requiredClues: ["clue_3", "clue_8", "clue_12"],
      consequences: {
        reputation: 10, influence: 12,
        dimitri_sokol_relationship: -40, clara_dumont_relationship: -10,
        nora_petrov_relationship: 10, karim_osman_relationship: 40,
        alexei_relationship: 40,
        propertyEffect: "riverside_reformed",
        rivalEffect: "dimitri_prosecuted",
        narrativeSummary: "Alexei testifies safely. Karim's status is protected. Dimitri faces prosecution. The scheme is dismantled carefully, protecting the vulnerable. It takes longer, but the community heals. Some powerful people remain dangerous."
      }
    }
  ],

  events: [
    { id: "evt_supply_shortage", category: "economic", title: "Supply Shortage", description: "A key supplier has delayed shipments. Prices are rising.", triggerCondition: "has_business", probability: 0.08, canRepeat: true, repeatCooldown: 10, choices: [{ text: "Absorb the cost", effects: { supplyCostMultiplier: 1.3, daysDuration: 3, reputation: 2 } }, { text: "Raise prices", effects: { saleValueMultiplier: 1.2, customerTrafficMultiplier: 0.85, daysDuration: 3 } }, { text: "Find alternative supplier", effects: { energyCost: 2, supplyCostMultiplier: 1.1, reputation: -1 }, condition: "energy >= 2" }], relatedCharacters: [], cityMemoryEntry: "Supply shortage affected local businesses" },
    { id: "evt_boom_day", category: "economic", title: "Shopping Boom", description: "An unexpected surge of customers! Everyone's buying.", triggerCondition: "has_business", probability: 0.06, canRepeat: true, repeatCooldown: 8, choices: [{ text: "Capitalize fully", effects: { customerTrafficMultiplier: 1.5, energyCost: 1, daysDuration: 1 } }, { text: "Serve normally", effects: { customerTrafficMultiplier: 1.2, daysDuration: 1 } }], relatedCharacters: [], cityMemoryEntry: "Shopping surge boosted local commerce" },
    { id: "evt_street_festival", category: "neighborhood", title: "Street Festival", description: "The neighborhood is hosting a street festival! Great for foot traffic.", triggerCondition: "true", probability: 0.04, canRepeat: true, repeatCooldown: 15, choices: [{ text: "Set up a booth", effects: { customerTrafficMultiplier: 1.8, energyCost: 2, cash: -10, daysDuration: 1, reputation: 3 }, condition: "has_business" }, { text: "Enjoy the festival", effects: { energy: 2, reputation: 1 } }], relatedCharacters: ["karim_osman"], cityMemoryEntry: "Street festival brought community together" },
    { id: "evt_construction", category: "neighborhood", title: "Nearby Construction", description: "Heavy construction nearby is disrupting businesses.", triggerCondition: "has_business_in_riverside", probability: 0.07, canRepeat: true, repeatCooldown: 12, choices: [{ text: "Complain to city hall", effects: { influence: -1, reputation: 1, customerTrafficMultiplier: 0.7, daysDuration: 3 }, condition: "influence >= 5" }, { text: "Adapt and wait", effects: { customerTrafficMultiplier: 0.75, daysDuration: 3 } }], relatedCharacters: ["clara_dumont"], cityMemoryEntry: "Construction disrupted local businesses" },
    { id: "evt_employee_conflict", category: "employee", title: "Workplace Disagreement", description: "Two of your employees are arguing about how things should be done.", triggerCondition: "employee_count >= 2", probability: 0.1, canRepeat: true, repeatCooldown: 8, choices: [{ text: "Mediate personally", effects: { energyCost: 1, morale: 10, loyalty: 5 } }, { text: "Let them work it out", effects: { morale: -5, reliability: -2 } }, { text: "Side with senior employee", effects: { seniorMorale: 10, juniorMorale: -10 } }], relatedCharacters: [], cityMemoryEntry: "Workplace conflict tested management" },
    { id: "evt_employee_milestone", category: "employee", title: "Employee Achievement", description: "One of your employees completed a major personal goal!", triggerCondition: "employee_count >= 1", probability: 0.03, canRepeat: true, repeatCooldown: 20, choices: [{ text: "Celebrate with a bonus", effects: { cash: -20, morale: 20, loyalty: 15, skill: 1 } }, { text: "Public recognition", effects: { morale: 10, loyalty: 8, reputation: 2 } }], relatedCharacters: [], cityMemoryEntry: "Employee achievement boosted team spirit" },
    { id: "evt_employee_poached", category: "employee", title: "Rival Recruitment Attempt", description: "A rival is trying to recruit one of your employees.", triggerCondition: "employee_count >= 1", probability: 0.08, canRepeat: true, repeatCooldown: 10, choices: [{ text: "Counter-offer with raise", effects: { wageIncrease: 5, loyalty: 15, morale: 10 } }, { text: "Talk to the employee", effects: { energyCost: 1, loyalty: 8, morale: 5 } }, { text: "Let them decide", effects: { loyalty: -5, leaveChance: 0.3 } }], relatedCharacters: ["svetlana_markov"], cityMemoryEntry: "Rival attempted to recruit employee" },
    { id: "evt_price_war", category: "rival", title: "Price War Declared", description: "A rival slashed prices in your area, trying to steal customers.", triggerCondition: "has_business", probability: 0.06, canRepeat: true, repeatCooldown: 12, choices: [{ text: "Match their prices", effects: { saleValueMultiplier: 0.7, customerTrafficMultiplier: 1.1, daysDuration: 5 } }, { text: "Focus on quality", effects: { qualityBonus: 0.1, customerTrafficMultiplier: 0.9, daysDuration: 5, reputation: 3 } }, { text: "Diversify products", effects: { energyCost: 2, supplyCost: 10, saleValueMultiplier: 1.05, daysDuration: 5 } }], relatedCharacters: ["svetlana_markov"], cityMemoryEntry: "Price war disrupted local market" },
    { id: "evt_rival_alliance", category: "rival", title: "Alliance Proposal", description: "A rival organization proposes a strategic alliance.", triggerCondition: "rival_neutral_or_friendly", probability: 0.04, canRepeat: true, repeatCooldown: 20, choices: [{ text: "Accept alliance", effects: { rivalAlliance: true, supplyCostMultiplier: 0.85, reputation: -3, influence: 5 } }, { text: "Decline politely", effects: { rivalRelationship: 5, reputation: 2 } }, { text: "Counter with modified terms", effects: { energyCost: 1, rivalRelationship: 10, supplyCostMultiplier: 0.9, reputation: 1 }, condition: "influence >= 5" }], relatedCharacters: ["lisette_valenti"], cityMemoryEntry: "Alliance offer shaped business landscape" },
    { id: "evt_negative_press", category: "rival", title: "Negative Press", description: "Someone is spreading damaging rumors about your business.", triggerCondition: "has_business", probability: 0.05, canRepeat: true, repeatCooldown: 10, choices: [{ text: "Issue a public statement", effects: { energyCost: 1, reputation: -2, influence: 2, daysDuration: 2 } }, { text: "Find the source", effects: { energyCost: 2, knowledge: 2, rivalRelationship: -10 } }, { text: "Ignore it", effects: { reputation: -5, daysDuration: 3 } }], relatedCharacters: ["svetlana_markov", "nora_petrov"], cityMemoryEntry: "Negative publicity tested reputation" },
    { id: "evt_vip_customer", category: "customer", title: "VIP Customer", description: "A wealthy and influential customer visits your business!", triggerCondition: "has_business", probability: 0.05, canRepeat: true, repeatCooldown: 15, choices: [{ text: "Give premium service", effects: { energyCost: 1, reputation: 5, influence: 2, cash: 15 } }, { text: "Treat normally", effects: { reputation: 1 } }], relatedCharacters: [], cityMemoryEntry: "VIP customer visit boosted reputation" },
    { id: "evt_customer_complaint", category: "customer", title: "Customer Complaint", description: "An unhappy customer is making a scene about poor quality.", triggerCondition: "has_business", probability: 0.07, canRepeat: true, repeatCooldown: 8, choices: [{ text: "Apologize and compensate", effects: { cash: -5, reputation: 3 } }, { text: "Explain your side", effects: { reputation: -2, influence: 1 } }, { text: "Ignore it", effects: { reputation: -5 } }], relatedCharacters: [], cityMemoryEntry: "Customer complaint challenged quality" },
    { id: "evt_new_regulation", category: "political", title: "New Regulation", description: "City Hall announced new business regulations.", triggerCondition: "has_business", probability: 0.04, canRepeat: true, repeatCooldown: 20, choices: [{ text: "Comply immediately", effects: { cash: -15, reputation: 5 } }, { text: "Seek exemption", effects: { energyCost: 2, influence: 3, cash: -5 }, condition: "influence >= 10" }, { text: "Protest through channels", effects: { energyCost: 1, reputation: -2, influence: 5 } }], relatedCharacters: ["clara_dumont"], cityMemoryEntry: "New regulation affected operations" },
    { id: "evt_election", category: "political", title: "Election Season", description: "Local elections are approaching. Politicians are making promises.", triggerCondition: "influence >= 5", probability: 0.03, canRepeat: true, repeatCooldown: 30, choices: [{ text: "Support a candidate", effects: { cash: -25, influence: 8, reputation: -2 } }, { text: "Stay neutral", effects: { influence: 2 } }, { text: "Endorse community candidate", effects: { cash: -10, influence: 4, reputation: 5 } }], relatedCharacters: ["clara_dumont", "karim_osman"], cityMemoryEntry: "Election season stirred political engagement" },
    { id: "evt_property_sale", category: "property", title: "Urgent Property Sale", description: "A property is being sold urgently at below market value.", triggerCondition: "reputation >= 5", probability: 0.03, canRepeat: true, repeatCooldown: 20, choices: [{ text: "Buy it immediately", effects: { cash: -150, property: "random", reputation: 3 } }, { text: "Investigate first", effects: { energyCost: 1, knowledge: 2, propertyDiscount: 10 }, condition: "energy >= 1" }, { text: "Pass", effects: {} }], relatedCharacters: ["elena_kosta"], cityMemoryEntry: "Property sale created opportunity" },
    { id: "evt_rent_increase", category: "property", title: "Rent Increase Notice", description: "Your landlord is raising the rent.", triggerCondition: "has_business_with_rent", probability: 0.06, canRepeat: true, repeatCooldown: 10, choices: [{ text: "Pay the increase", effects: { dailyRentMultiplier: 1.15, reputation: 1 } }, { text: "Negotiate", effects: { energyCost: 1, dailyRentMultiplier: 1.05 }, condition: "relationship_with_landlord >= 10" }, { text: "Refuse and find alternatives", effects: { energyCost: 2, reputation: -2 } }], relatedCharacters: ["svetlana_markov"], cityMemoryEntry: "Rent increase challenged stability" },
    { id: "evt_mysterious_note", category: "mystery", title: "Anonymous Note", description: "You found a note slipped under your door. 'Follow the money. Warehouse 7. Midnight.'", triggerCondition: "day >= 5", probability: 0.08, canRepeat: false, choices: [{ text: "Investigate the warehouse", effects: { energyCost: 2, knowledge: 3 }, condition: "energy >= 2" }, { text: "Ask Tom about it", effects: { energyCost: 1, trust: -5, clue: "clue_6" } }, { text: "Ignore it", effects: { knowledge: -1 } }], relatedCharacters: ["dimitri_sokol", "tom_brady"], cityMemoryEntry: "Anonymous note hinted at something deeper" },
    { id: "evt_mystery_witness", category: "mystery", title: "Nervous Witness", description: "A stranger approaches you near the warehouse. They look terrified.", triggerCondition: "has_clue_count >= 3", probability: 0.1, canRepeat: false, choices: [{ text: "Hear them out", effects: { energyCost: 1, trust: 10, clue: "clue_3", relationship: 15 } }, { text: "Bring them somewhere safe", effects: { energyCost: 2, trust: 15, relationship: 25, reputation: 3 } }, { text: "Stay cautious, walk away", effects: { trust: -5 } }], relatedCharacters: ["dimitri_sokol_jr"], cityMemoryEntry: "Witness approached with information" },
    { id: "evt_character_favor", category: "relationship", title: "Request for Help", description: "A character asks for a favor. It'll cost you, but they'll owe you.", triggerCondition: "any_relationship >= 15", probability: 0.06, canRepeat: true, repeatCooldown: 12, choices: [{ text: "Help them", effects: { cash: -15, energyCost: 1, relationship: 15, trust: 10, leverage: 1 } }, { text: "Help but ask for something", effects: { cash: -10, energyCost: 1, relationship: 5, leverage: 2, trust: -2 } }, { text: "Decline politely", effects: { relationship: -5, trust: -3 } }], relatedCharacters: [], cityMemoryEntry: "Favor strengthened or strained relationship" },
    { id: "evt_betrayal", category: "relationship", title: "Betrayal", description: "Someone you trusted shared your business info with a rival.", triggerCondition: "any_trust < 20", probability: 0.04, canRepeat: false, choices: [{ text: "Confront them", effects: { energyCost: 1, trust: -15, relationship: -20, reputation: 3 } }, { text: "Use it as leverage", effects: { leverage: 2, trust: -10, relationship: -10 } }, { text: "Cut ties quietly", effects: { relationship: -30, trust: -20, reputation: 1 } }], relatedCharacters: ["tom_brady"], cityMemoryEntry: "Betrayal revealed the cost of misplaced trust" }
  ],

  upgrades: [
    { id: "upg_stall_1", businessId: "market_stall", level: 1, name: "Better Display Shelf", cost: 30, qualityBonus: 0.1, capacityBonus: 5 },
    { id: "upg_stall_2", businessId: "market_stall", level: 2, name: "Expanded Product Range", cost: 60, qualityBonus: 0.15, capacityBonus: 8 },
    { id: "upg_stall_3", businessId: "market_stall", level: 3, name: "Premium Goods Section", cost: 120, qualityBonus: 0.2, capacityBonus: 12 },
    { id: "upg_coffee_1", businessId: "coffee_cart", level: 1, name: "Premium Bean Supplier", cost: 25, qualityBonus: 0.1, capacityBonus: 8 },
    { id: "upg_coffee_2", businessId: "coffee_cart", level: 2, name: "Pastry Partnership", cost: 55, qualityBonus: 0.15, capacityBonus: 10 },
    { id: "upg_coffee_3", businessId: "coffee_cart", level: 3, name: "Second Cart Permit", cost: 100, qualityBonus: 0.2, capacityBonus: 15 },
    { id: "upg_cafe_1", businessId: "small_cafe", level: 1, name: "Expanded Seating", cost: 50, qualityBonus: 0.1, capacityBonus: 8 },
    { id: "upg_cafe_2", businessId: "small_cafe", level: 2, name: "Kitchen Upgrade", cost: 110, qualityBonus: 0.15, capacityBonus: 10 },
    { id: "upg_cafe_3", businessId: "small_cafe", level: 3, name: "Rooftop Terrace", cost: 200, qualityBonus: 0.2, capacityBonus: 15 },
    { id: "upg_repair_1", businessId: "repair_service", level: 1, name: "Better Tools", cost: 40, qualityBonus: 0.1, capacityBonus: 4 },
    { id: "upg_repair_2", businessId: "repair_service", level: 2, name: "Electronics Repair", cost: 90, qualityBonus: 0.15, capacityBonus: 6 },
    { id: "upg_repair_3", businessId: "repair_service", level: 3, name: "Appraisal Service", cost: 170, qualityBonus: 0.2, capacityBonus: 8 },
    { id: "upg_conv_1", businessId: "convenience_store", level: 1, name: "Extended Hours", cost: 60, qualityBonus: 0.1, capacityBonus: 10 },
    { id: "upg_conv_2", businessId: "convenience_store", level: 2, name: "Fresh Food Section", cost: 130, qualityBonus: 0.15, capacityBonus: 12 },
    { id: "upg_conv_3", businessId: "convenience_store", level: 3, name: "ATM Partnership", cost: 250, qualityBonus: 0.2, capacityBonus: 15 },
    { id: "upg_negotiation", businessId: "player", level: 1, name: "Negotiation Course", cost: 50, description: "Improves all negotiation outcomes by 10%.", negotiationBonus: 0.1 },
    { id: "upg_marketing", businessId: "player", level: 1, name: "Marketing Basics", cost: 40, description: "All businesses gain +10% customer traffic.", customerTrafficBonus: 0.1 },
    { id: "upg_reputation", businessId: "player", level: 1, name: "Community Membership", cost: 30, description: "Reputation gains increased by 15%.", reputationBonus: 0.15 }
  ],

  goods: [
    { id: "produce", name: "Fresh Produce", buyPrice: 3, sellPrice: 5, category: "retail", weight: 1 },
    { id: "coffee_beans", name: "Coffee Beans", buyPrice: 4, sellPrice: 7, category: "food", weight: 1 },
    { id: "tools", name: "Basic Tools", buyPrice: 8, sellPrice: 13, category: "repair", weight: 2 },
    { id: "snacks", name: "Packaged Snacks", buyPrice: 2, sellPrice: 4, category: "retail", weight: 1 },
    { id: "electronics", name: "Small Electronics", buyPrice: 12, sellPrice: 20, category: "repair", weight: 2 },
    { id: "household", name: "Household Goods", buyPrice: 5, sellPrice: 9, category: "retail", weight: 1 }
  ],

  tutorialSteps: [
    { id: "tut_1", trigger: "game_start", text: "Welcome to the city. You have €100 and big plans. Let's get started.", highlight: "cash" },
    { id: "tut_2", trigger: "first_action", text: "Every action costs time and energy. Choose wisely — you have limited energy each day.", highlight: "energy" },
    { id: "tut_3", trigger: "first_earning", text: "Money earned! But remember — businesses have daily expenses too.", highlight: "cash" },
    { id: "tut_4", trigger: "first_visit", text: "Explore the city map. Each location offers different opportunities.", highlight: "map" },
    { id: "tut_5", trigger: "first_conversation", text: "People remember how you treat them. Relationships open doors — or close them.", highlight: "relationships" },
    { id: "tut_6", trigger: "first_business", text: "You're a business owner now! Check your daily revenue and expenses carefully.", highlight: "business" },
    { id: "tut_7", trigger: "first_employee", text: "Your first employee! Take care of them — they're the backbone of your business.", highlight: "employees" },
    { id: "tut_8", trigger: "day_3", text: "The city is watching. Your choices shape the neighborhoods around you.", highlight: "news" },
    { id: "tut_9", trigger: "first_save", text: "Your progress is saved automatically. You can also use manual save slots.", highlight: "save" },
    { id: "tut_10", trigger: "first_consequential_choice", text: "That choice had consequences. In this city, nothing happens in isolation.", highlight: "news" }
  ]
};
